### ISSUE TITLE
W repozytorium nie ma tagu walking-skeleton opisanego na stronie 91

### ISSUE THREAD

**Issue by redwitchproject** [Enforcer/implementing-the-clean-architecture#3]

**Comment by Enforcer** [comment]
Dziękuję za zwrócenie uwagi! Przeoczenie - pierwszy commit był tak opisany, ale brakowało taga. Dodałem i wypchnąłem

**Comment by redwitchproject** [comment]
Super - commit znalazłem, ale utworzyłem issue żeby wszystko było zgodnie z tym co jest napisane w książce :)
